### ISSUE TITLE
[1.7.10] Class not being recognized

### ISSUE THREAD

**Issue by Alex33212** [ForestryMC/Binnie#255]
In both the 2.0.21 and 2.0-pre18 versions for 1.7.10, my game crashes during startup with the following error:
"cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: binnie/extrabees/apiary/TileExtraBeeAlveary".
However, in the path binnie/extrabees/apiary, there is a file called TileExtraBeeAlveary.class.
What's going on here?

**Comment by mezz** [comment]
Thanks for the report!
Please make sure to remove any Binnie bug-fixing mods like BinniePatcher, they are not needed with these new versions.
If you still crash please upload the crash log to https://gist.github.com/ and link it here.

**Comment by Alex33212** [comment]
the only mod I installed was the core Binnie's Mods. Here's the crash log:
https://gist.github.com/Alex33212/343b50f113ce41f605846f7544179822

**Comment by KorDum** [comment]
Hm. Are you change class with some bytecode editor?
I'm playing with 2.0.21 version and I don't have any problems.
Can you remove all mods and check it with Forestry and Binnie only? And gradually adding mods. Maybe some mod patch the code...

**Comment by Alex33212** [comment]
well, given that I'm adding Binnie's Mods to the Tekkit Legends modpack, I can't really remove mods without seriously messing things up.

**Comment by mezz** [comment]
Oh, I see you're using Forestry 3.6. 
This new Binnie's only works with the latest Forestry, 4.2.16.

**Comment by mezz** [comment]
@KorDum for 1.7.10 Binnie's please add a minimum required version for Forestry. 
Here's an example from 1.11.2
https://github.com/ForestryMC/Binnie/blob/master-MC1.11.2/src/main/java/binnie/core/BinnieCore.java#L61

**Comment by KorDum** [comment]
@mezz I'll do it, thanks!
